Added workplan changed event to have the possibility to react on changes
PHOENIXCONTACT/MORYX-Platform pull request #105
Opened 2021-03-18 15:40 UTC by slawor

It is necessary to have an event about a changed workplan to be able to react on this change.

2021-03-19 08:03 UTC, Toxantron commented
Since we have to extend the workplan API anyway. Should we include a `SourceId` for workplans. This could be helpful for future changes when workplans are cloned, versioned, ...
@dbeuchler ?

2021-03-19 08:05 UTC, Toxantron requested changes

2021-03-19 08:05 UTC, Toxantron commented on src/Moryx/Workflows/API/IWorkplanManagement.cs
> +    public interface IWorkplanManagement : IWorkplans
Can you disable the Deprecated warning for this usage?

2021-03-19 08:07 UTC, dbeuchler commented
> Since we have to extend the workplan API anyway. Should we include a `SourceId` for workplans. This could be helpful for future changes when workplans are cloned, versioned, ...
> @dbeuchler ?

yes... source id can be helpfull

2021-03-19 11:48 UTC, slawor commented
> Since we have to extend the workplan API anyway. Should we include a `SourceId` for workplans. This could be helpful for future changes when workplans are cloned, versioned, ...
> @dbeuchler ?

Can we add it if we need it in the future? I would like to address only one problem

2021-03-22 14:52 UTC, Toxantron approved these changes

2021-04-11 18:53 UTC, Toxantron commented
Since the requirement has disappeared, could we do this against future without obsolotes?

2021-04-26 07:39 UTC, closed without merging